version: "3.5"

services:
  postgres:
    container_name: fiverr
    image: postgres
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
